import type { Metadata } from "next";
import "./globals.css";
import { NavBar, User } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-base flex h-[100dvh] w-screen">
        <NavBar />
        <User />
        {children}
      </body>
    </html>
  );
}
